source/Libraries/GogLibrary/GogLibrary.cs
GOG: Fix in case user library stats data could not be obtained during library import or GOG profile has been disabled in privacy settings by user
Fixes https://github.com/JosefNemec/PlayniteExtensions/issues/66
Edit: The actual cause of the issue was that the profile privacy was set to maximum and GOG returns a blank page for those profiles. While the issue is fixed, we need to see if there's a way to still get that data in those profiles
Edit 2: Nothing can be done about it. Disabling this option means not even you can access that data when logged in https://www.gog.com/account/settings/privacy
=> GOG: Fix in case user library stats data could not be obtained during library import or GOG profile has been disabled in privacy settings by user

source/Libraries/RockstarLibrary/RockstarGamesLibrary.cs
Fixes #69
Built and confirmed working
=> RockstarGamesLibrary: Fix GTA V not being detected as installed after its latest update #69

source/Libraries/RockstarLibrary/RockstartGames.cs
I just bought the gta trilogy definitive editions from the Rockstar Launcher. Wanted to add the games to my Playnite game collection. 
I compiled the rockstar extension and tested it on my machine. I got all 3 games to show up as installed in Playnite, got metadata to download for each of the games, and hitting "Play" started each of the games successfully.
=> Add GTA Definitive editions to Rockstar extension

source/Libraries/ItchioLibrary/Butler.cs, source/Libraries/ItchioLibrary/Models/FetchGameRecords.cs, source/Libraries/ItchioLibrary/Models/FetchProfileOwnedKeys.cs
It is caused by the local butler.db not being updated.
If the stale key is true in the query response, re-query with refresh key are required. 
I've modified the code to get the intended behavior. 
For importing owned games, the refresh key was fixed to true. 
But, I also modified the code to check the stale key and re-query.
I've built and tested this code and it's working as expected.
Thank you.
=> Itch.io: Fix issue that old collections are imported instead of latest collections.

source/Libraries/HumbleLibrary/HumbleLibrary.cs
Fix games incorrectly being marked as installed in cases where the detected game path is not currently available. Useful in cases where games are installed on an external usb that could be disconnected.
Built and tested.
=> Humble fix isInstalled detection if game unavailable

source/Libraries/EpicLibrary/EpicLibrary.cs
Epic: Fix returning games from GetInstalledGames() if directory not detected
I previously sent a PR that incorrectly did this and marked games as uninstalled instead in the method. This PR fixes it to be in line with what you indicated me in this PR for Humble https://github.com/JosefNemec/PlayniteExtensions/pull/156
=> Epic Library: Fix returning games from GetInstalledGames() if directory not detected

source/Libraries/RockstarLibrary/RockstarGamesController.cs
Rework to use `-launchTitleInFolder`. Doesn't require waiting on process exit. Works with all tested games below.
Tested with:
- Red Dead Redemption 2
- L.A. Noire
- Grand Theft Auto IV
- Grand Theft Auto: San Andreas
- Max Payne 3
=> RockstarGamesLibrary: Fix time tracking

source/Libraries/XboxLibrary/XboxGameController.cs
Xbox: Fix stopwatch being started before process is started
=> Xbox: Fix stopwatch being started before process is started

source/Libraries/UplayLibrary/UplayGameController.cs
Uplay: Fix stopwatch being started before process is started
=> Uplay: Fix stopwatch being started before process is started

source/Libraries/BattleNetLibrary/BattleNetGameController.cs
Battle.net: Fix stopwatch being started before process is started
=> Battle.net: Fix stopwatch being started before process is started

source/Libraries/SteamLibrary/SteamGameController.cs
Steam: Fix stopwatch being started before process is started
It makes more sense to start the stopwatch only after the game process has been detected as running as this will provide a more accurate Playtime.
Built and tested
=> Steam: Fix stopwatch being started before process is started

source/Libraries/EpicLibrary/Services/EpicAccountClient.cs
Hiya!
I've managed to fix Epic authentication by changing it to `authorization_code` based.
It includes a different `loginUrl` (specifically the redirection parameter), which is now returning code directly. `clientId` parameter in the URL is username taken from `authEncodedString` (as on the screenshot). Since `authorization_code` is delivered directly, `getExchangeToken` is no longer needed. I didn't delete the method, just skipped the call.
Everything seems to be working fine - I've cleared out tokens.json file, cleared cache, re-authorized with Epic successfully and all my games were imported, both installed and non-installed.
Fixes: https://github.com/JosefNemec/PlayniteExtensions/issues/207 https://github.com/JosefNemec/Playnite/issues/3039 …
=> Changes authorization method for Epic to authorization_code based

source/Libraries/SteamLibrary/SteamShared/MetadataProvider.cs
Steam demos don't get descriptions or tags. This will fix that (once the other PR for the is merged for the tags).
=> Get Steam metadata for demos from the main game

source/Libraries/UplayLibrary/Properties/AssemblyInfo.cs, source/Libraries/UplayLibrary/UplayClient.cs, source/Libraries/UplayLibrary/UplayLibrary.cs, source/Libraries/UplayLibrary/UplayMetadataProvider.cs, source/Libraries/UplayLibrary/extension.yaml
I've noticed there are still messages using 'Uplay' instead of 'Ubisoft Connect', so I've cleaned that up.
=> Cleans up Ubisoft Connect naming

source/Libraries/SteamLibrary/SteamShared/MetadataProvider.cs, source/Metadata/UniversalSteamMetadata/UniversalSteamMetadataProvider.cs
Also fixes canceling out of manual metadata search resulting in a metadata assignment choice window with a pc_windows platform
=> Steam: Added platform metadata

source/Libraries/GogLibrary/GOGMetadataProvider.cs, source/Libraries/GogLibrary/GogLibrary.csproj, source/Libraries/GogLibrary/packages.config
Removes garbage promotional section that GOG adds to all game descriptions during sale periods.
Built and tested.
=> GOG: Remove sale promos from game descriptions

source/Metadata/UniversalSteamMetadata/UniversalSteamMetadata.cs
Currently the search uses the search term as it is and for games like `Command & Conquer Remastered Collection` that have characters that need encoding, like `&`,  `=`,  `?`, etc. this causes an issue as the produced url is this:
https://store.steampowered.com/search/?term=Command & Conquer Remastered Collection&ignore_preferences=1&category1=998
Which causes the search to be erroneous, in this case turning as `Command` only:
This change corrects it to fix searches when the search includes any of the problematic characters:
https://store.steampowered.com/search/?term=Command%20%26%20Conquer%20Remastered%20Collection&ignore_preferences=1&category1=998
=> Steam Metadata: Fix incorrect searches when search has special characters

source/Metadata/UniversalSteamMetadata/UniversalSteamMetadata.cs
Steam has been changing the results page and now the release date html element has whitespace on the sides.
Before:
After:
=> UniversalSteamMetadata: Fix description text having whitespace

source/Libraries/XboxLibrary/Models/AuthenticationData.cs, source/Libraries/XboxLibrary/Services/XboxAccountClient.cs
Based on https://github.com/OpenXbox/xbox-webapi-python as suggested in #338.
The `client_id` and `client_secret` constants need to be updated with values from your Playnite app registration in Azure. I tested the code with values from an app registration I created in my Azure account. I followed [the instructions from the Python project](https://github.com/OpenXbox/xbox-webapi-python#xbox-webapi), except for the Redirect URI I used `https://login.live.com/oauth20_desktop.srf` as can be seen from code, because I couldn't manage to read the authorization code from the web view if I used localhost as suggested there.
=> Implement new Xbox Live authentication method

source/Libraries/XboxLibrary/Services/XboxAccountClient.cs
I made a copy-paste error in my original implementation and passed refresh token parameter incorrectly which caused the refresh token operation to fail with a 400 Bad Request response.
=> Provide refresh token param correctly

source/Libraries/ItchioLibrary/ItchioGameController.cs
There exists an Itch.io url to pass as a command line argument for installing. URLs of the form 'itch://install?game_id=###' will prompt the itch client to open the installation dialog box.
I believe this addresses the issue here: https://github.com/JosefNemec/Playnite/issues/3203
I've built the extension locally and loaded into Playnite. Installing Itch games has the desired behavior. 
The itch.io source I referenced for the install feature is here: https://github.com/itchio/itch/blob/102011c51dc26a3142795c67394c365bb09cb309/src/main/reactors/url.ts#L96
I confirmed that the Game ID argument inside of Playnite matches what the Itch Client is expecting. I chose an Itch game and used Playnite to lookup the Game Id. I then ran the url using the Windows Run command and had Itch.Io work as …
=> [#3203] Add install support for Itchio

source/Libraries/EpicLibrary/EpicLibrary.cs
They require Ubisoft Connect to launch, so skip importing them to prevent duplicates ♻️.
=> Epic Games: Skip importing Ubisoft games

source/Metadata/UniversalSteamMetadata/UniversalSteamMetadata.cs
Currently games don't show in search results if game doesn't have English or any of the user languages. This parameter removes languages narrowing to show all games:
https://store.steampowered.com/search/?term=nayuta+no+kiseki&ignore_preferences=1&category1=998&ndl=1
Before:
After:
=> UniversalSteamMetadata: Fix missing games in search

source/Libraries/EpicLibrary/EpicLibrary.cs
Looks like there is already condition to skip importing DLCs, but it's not working.
From some time also weird launchable DLCs exists (like Rocket Racing), so I excluded them, but installing them doesn't work currently unfortunately, Epic says that base game is required.
=> Epic: Skip importing non-launchable DLCs

source/Libraries/EpicLibrary/EpicLibrary.cs, source/Libraries/EpicLibrary/Models/CatalogResponse.cs, source/Libraries/EpicLibrary/Services/EpicAccountClient.cs
I noticed that still some non-launchable DLCs (ex. Dying Light The Following), soundtracks and artbooks are imported.
Apparently not all of them have "addons" category, but I found better way.
=> Epic: Skip importing unnecessary DLCs

source/Libraries/AmazonGamesLibrary/Models/EntitlementsRequest.cs, source/Libraries/AmazonGamesLibrary/Services/AmazonAccountClient.cs
- Fixes failing to obtain games during library update. (#401)
- While not needed, I added two missing parameters in the request body and updated the user agent for good measure.
=> Amazon: Fix failing to obtain game library (#401)

source/Libraries/SteamLibrary/SteamLibrary.cs, source/Libraries/SteamLibrary/SteamShared/MetadataProvider.cs
This affects both the Steam library and Steam metadata plugin.
**1. Remove trailing whitespace in game names:** Not a major issue but sometimes games contain unintended trailing whitespace. This has gone undetected for many years and is more common than I'd have thought, in my library I found around 40~50 games with this issue. It looks to be an issue in the returned data from Steam, but can also happen if there's a Trademark character, which is currently removed, that is leaded by whitespace. While not a critical issue, this has the potential to affect other parts of the application or plugins in situations where the game name is used for different scenarios, including matching using the name.
**2. Remove trademark characters when downloading metadata:** Currently these characters are …
=> Steam: Library update and metadata download game name fixes

source/Libraries/SteamLibrary/SteamGameController.cs
Fixes:
- Freezing Playnite UI during uninstall process while obtaining installed games: https://github.com/JosefNemec/PlayniteExtensions/blob/7c471edfeea4ed1384f97c14ad76c48988453248/source/Libraries/SteamLibrary/SteamGameController.cs#L123
Issue doesn't occur in Install controller because the Watcher is already running in a Task.
Before:
https://github.com/user-attachments/assets/f4cb244b-1a67-4c78-bd6e-1121322f8486
After:
https://github.com/user-attachments/assets/32bce657-2e0c-4132-ac9b-ff35adefcc82
=> Steam: Fix freezes during Uninstall
